export default [
  { name: "1.jpg", color: "light" },
  { name: "2.jpg", color: "light" },
  { name: "3.jpg", color: "dark" },
  { name: "4.jpg", color: "dark" },
  { name: "5.jpg", color: "dark" },
  { name: "6.jpg", color: "dark" },
  { name: "7.jpg", color: "dark" },
  { name: "8.jpg", color: "dark" },
  { name: "9.jpg", color: "light" },
  { name: "11.jpg", color: "dark" },
  { name: "12.jpg", color: "dark" },
  { name: "13.jpg", color: "dark" },
  { name: "14.jpg", color: "dark" },
  { name: "15.jpg", color: "dark" },
  { name: "16.jpg", color: "dark" },
  { name: "17.jpg", color: "dark" },
  { name: "18.jpg", color: "dark" },
  { name: "19.jpg", color: "light" },
  { name: "20.jpg", color: "dark" }
];
