export default [
  { image: "1.jpg", color: "light" },
  { image: "2.jpg", color: "light" },
  { image: "3.jpg", color: "dark" },
  { image: "4.jpg", color: "dark" },
  { image: "5.jpg", color: "dark" },
  { image: "6.jpg", color: "light" },
  { image: "7.jpg", color: "dark" },
  { image: "8.jpg", color: "dark" },
  { image: "9.jpg", color: "light" },
  { image: "11.jpg", color: "dark" },
  { image: "12.jpg", color: "dark" },
  { image: "13.jpg", color: "dark" },
  { image: "14.jpg", color: "dark" },
  { image: "15.jpg", color: "dark" },
  { image: "16.jpg", color: "dark" },
  { image: "17.jpg", color: "dark" },
  { image: "18.jpg", color: "dark" },
  { image: "19.jpg", color: "light" },
  { image: "20.jpg", color: "dark" }
];
